id: P48836D23
initial_creation_type: input
source_metadata:
  Title: Essays on the History of Buddhism
  Editor: '-'
  Publisher: Kyoto University
  Place of Publication: Kyoto
  Year: '1961'
  Kalpoktam훮r카c카s훮dhanam:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: June, 2017
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:02:25.708494'
last_modified_at: '2022-03-08T17:02:25.708504'
